### ISSUE TITLE
Question about results

### ISSUE THREAD

**Issue by insight97-maker** [UARK-AICV/MEGANet#2]
Dear author, the result for detection results was poor. I don't know why, are there thing i ignored in my operation?
![1f75430a83c2da397423de85d9bdfe2](https://github.com/UARK-AICV/MEGANet/assets/172048403/bb89a445-7157-4d17-a484-a281e64d7a4b)

**Comment by wuhuqifei0** [comment]
> 尊敬的作者，检测结果很差。我不知道为什么，在我的操作中有什么我忽略了什么吗？ ![1f75430a83c2da397423de85d9bdfe2](https://private-user-images.githubusercontent.com/172048403/337674853-bb89a445-7157-4d17-a484-a281e64d7a4b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzY4NTksIm5iZiI6MTcxODE3NjU1OSwicGF0aCI6Ii8xNzIwNDg0MDMvMzM3Njc0ODUzLWJiODlhNDQ1LTcxNTctNGQxNy1hNDg0LWEyODFlNjRkN2E0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNzE1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWI2NjFhZGI4YjhmNDE0ZWE1NjNmNGM1ZWQ4NThhMGNmNWQ1MDYwN2Y1NWYwMjU5NjNmNzZmNTczM2ZkNWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BaKJ4aU6kYKdMe40tI-wX8RyFNASYrNdfpQ5ld4u3Iw)

Hello.Did you encounter any issues during your training? The size of tensor a (7) must match the size of tensor b (8) at non-singleton dimension 3.

**Comment by tanbuinhat** [comment]
Hi, sorry for late response!

Can you check the results again! It seems like you are using the wrong result path, or there is some issue with the result.

**Comment by liu-chuanjun** [comment]
Did you solve the problem?
