### ISSUE TITLE
Why is only 1 laplacian layer used in decoder?

### ISSUE THREAD

**Issue by Billy-ZTB** [UARK-AICV/MEGANet#6]
![image](https://github.com/user-attachments/assets/c2e1d5e7-23c8-44b1-bd8d-995af5cd7207)
![image](https://github.com/user-attachments/assets/ac693229-1ecf-46b5-9036-4a6609dd758a)
You calculated several layers but only extracted 1 of them for decoder?

**Comment by tanbuinhat** [comment]
Thank you for your question!

In our paper, we have the ablation study for using our proposed and obtaining the features from the Laplacian pyramid. It's shown in Table 4.

**Comment by Billy-ZTB** [comment]
Thanks for your reply! I will read your paper carefully.
